name: CI Skip

on:
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"
      - ".gitignore"
      - "README.md"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: "test"
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping tests"
